export const REGISTER_USER = 'REGISTER_USER';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const OPEN_MODAL_REGISTRATION = 'OPEN_MODAL_REGISTRATION';
export const CLOSE_MODAL_REGISTRATION = 'CLOSE_MODAL_REGISTRATION';
