export const WELCOME_IF_NOT_USER = 'WELCOME_IF_NOT_USER';
export const CLOSE_WELCOME_IF_NOT_USER = 'CLOSE_WELCOME_IF_NOT_USER';

export const TOGGLE_DASHBOARD = 'TOGGLE_DASHBOARD';
export const SELECT_ITEM_PLAYLIST = 'SELECT_ITEM_PLAYLIST';
export const TOGGLE_LIKED_ITEM = 'TOGGLE_LIKED_ITEM';

export const REGISTER_USER = 'REGISTER_USER';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const OPEN_MODAL_REGISTRATION = 'OPEN_MODAL_REGISTRATION';
export const CLOSE_MODAL_REGISTRATION = 'CLOSE_MODAL_REGISTRATION';
